### ISSUE TITLE
Different FID results

### ISSUE THREAD

**Issue by OwalnutO** [huangjiadidi/PUGAN#1]
Very interesting work!

Some differences exist when I try to reproduce the results in your paper:

1) What is the pattern of the pi for the results in table1 and table2? Is the basic pattern that initialized as 0.1 and increase it to 0.7? For the cat-64 dataset, I get a little bit better FID score with pi equal to 0.3 for the whole training process, compared with the results shown in table1. 

2)As shown in figure4, with any patterns of the pi, at the first 10000 iterations, all models get high FID results (above 30), but the result shown in table1 for cat-64 suggests that the max fid is just 18.99. Is there something I missed?

Thanks~

**Comment by huangjiadidi** [comment]
Dear OwalnutO
    Thank you for your interest in this work!
    For question 1: the pattern used in table1 and table 2 is basic pattern, which is 0.3 to 0.7. The better results you got in fixed 3 version could be caused by randomness of training. To be mentioned that, the pi is a hyper-parameter which indicates the assumed proportion of real data in the mixed data. As you can see in table 2, different pi might just lead to minor differences during our experiments, but the fixed 5 version achieves the best performance in the end. We believe that it is caused by it matchs the real proportion at that time. However, it doesn't mean a bad assumption could lead much worse result. How to get a better pi (or a changing pattern of pi) could be our furture work.

  For question2: The table1 compares the FID results within 20k to 100k epochs. We want to show that the PUGAN algorithm can achieve more stable performance during the training process, with lower SD and better results. 

 Regards

**Comment by OwalnutO** [comment]
Thanks for your reply.

I would like to make my question2 more clear.
<img width="275" alt="2" src="https://user-images.githubusercontent.com/24652623/79036101-629fcd80-7bf7-11ea-9f8c-1017ee7a94b2.PNG">

<img width="199" alt="1" src="https://user-images.githubusercontent.com/24652623/79036105-6a5f7200-7bf7-11ea-82ba-de0dfae108c8.PNG">

As suggests in Figure 4, at the first 10000 iterations, all models get a high FID score (above 30). But as shown in Table1, the highest FID score for PUSGAN is only 18.99, even not above 20. So I want to know that is the Figure wrong? or I just miss something?

**Comment by huangjiadidi** [comment]
The figure 4 doesn't have any mistake. As I mentioned before, the comparisons in table2 are within 20k to 100k itres. The main purpose of table 2 is trying to compare the stability of models. Since the models haven't converge at first 10k (as you can see in figure 4), it is unfair to use the data of first 10k itres for comparison.

**Comment by OwalnutO** [comment]
Thanks, I got it.

Maybe you should mention this setting more clear in the first paragraph in  Section 4.2, as you just mention that the results in table2 are calculated every 10000 iterations. Besides, for my experiment, I got the Fid 18.66 at the first 10000 iterations, which is still not same with Figure 4. I will check my settings, anyway, thanks for your reply~

**Comment by OwalnutO** [comment]
Thanks, I got it.

Maybe you should mention this setting more clear in the first paragraph in  Section 4.2, as you just mention that the results in table2 are calculated every 10000 iterations. Besides, for my experiment, I got the Fid 18.66 at the first 10000 iterations, which is still not same with Figure 4. I will check my settings, anyway, thanks for your reply~
